services:
  api:
    build:
      context: ./apieventos
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - backend-network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - api
    networks:
      - backend-network

networks:
  backend-network:
